### ISSUE TITLE
React Native 세팅

### ISSUE THREAD

**Issue by josworks27** [santa-close/santa-close-client#1]

**Comment by josworks27** [comment]
@lifeisegg123 
https://github.com/WrathChaos/react-native-typescript-boilerplate
이거 어때요 ?? 더 좋은거 있으면 알려주세요 ㅎㅎ

**Comment by lifeisegg123** [comment]
@josworks27 
저거는 rn 버전이 너무 낮아서 또 고통받을거 같네여..
저희 앱에서 크게 네이티브 기능 쓸일 없으면 expo로 만들어도 괜찮을거 같아요!

**Comment by josworks27** [comment]
expo 좋네요 ㅋㅋㅋ rn계의 cra죠?

**Comment by lifeisegg123** [comment]
cra보다는 next에 좀더 근접하지 않나 생각해봅니다 ㅎㅎ

**Comment by josworks27** [comment]
굳굳 좋아요 ㅋㅋㅋ
그럼 괜찮으시면 이슈에 있는 rn 초기 세팅 좀 부탁드려도 될까여

**Comment by lifeisegg123** [comment]
안되는데요? ㅋㅋㅋㅋ

**Comment by josworks27** [comment]
두식이한테 부끄러운 주인되지 맙시다 으휴

**Comment by lifeisegg123** [comment]
카카오 로그인을 app쪽에서 구현하려면 rn cli로 만드는게 나을수 있을거 같은데 어떠신가요?

**Comment by josworks27** [comment]
expo 지원이 안돼요??

**Comment by lifeisegg123** [comment]
대충 보니까 eject해서 써야되는거 같아요! 근데 eject 할 거 같으면 차라리 첨부터 rn cli로 만드는게 낫지 않나 싶어서요

**Comment by josworks27** [comment]
웹뷰로 하는데 eject해야 해요???

**Comment by lifeisegg123** [comment]
카카오 로그인을 rn에서 네이티브로 처리하려면 해야될것 같고 웹뷰로 하려면 안해도 됩니다

**Comment by josworks27** [comment]
토큰 스토리지에 저장할 필요성이 있으면 네이티브로 하는게 좋을것 같은데 어떻게 생가하세요??

**Comment by lifeisegg123** [comment]
그럼 네이티브로 하시조 rn cli로 세팅하겠습니다!
