### ISSUE TITLE
브릿지 구현

### ISSUE THREAD

**Issue by lifeisegg123** [santa-close/santa-close-client#88]

**Comment by josworks27** [comment]
![3A4EC501-D25D-438C-AA96-A62087FA9A33_1_102_o](https://user-images.githubusercontent.com/48130830/167181678-2a3d997d-025d-45c8-93e3-96fcea64b066.jpeg)

**Comment by josworks27** [comment]
https://jooonho.com/react/2022-03-20-webview-comunication/
